---
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-signin: >-
      https://nginx-oauth.greenpeace.org/oauth2/p4/start?rd=https://$host$uri
    nginx.ingress.kubernetes.io/auth-url: >-
      https://nginx-oauth.greenpeace.org/oauth2/p4/auth
  tls:
    - secretName: kibana-tls
      hosts:
        - prod.kibana.p4.greenpeace.org
  enabled: true
  hosts:
    - prod.kibana.p4.greenpeace.org
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 2Gi
