---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: elastic
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-signin: >-
      https://nginx-oauth.greenpeace.org/oauth2/p4/start?rd=https://$host$uri
    nginx.ingress.kubernetes.io/auth-url: >-
      https://nginx-oauth.greenpeace.org/oauth2/p4/auth
spec:
  tls:
    - secretName: kibana-tls 
      hosts:
        - kibana.p4.greenpeace.org
  rules:
    - host: kibana.p4.greenpeace.org
      http:
        paths:
        - path: /
          backend:
            serviceName: kibana
            servicePort: 5601
