---
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.p4.greenpeace.org
  enabled: true
  hosts:
    - kibana.p4.greenpeace.org
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 2Gi
